version: "3.5"
services:
  server:
    container_name: backend
    image: backend-dotnet
    build: .
    depends_on:
      - api
      - backend-postgres
    ports:
      - "8081:80"
    networks:
      - api-network
      - backend-db
  api:
    container_name: api
    image: api-backend-dotnet
    build: ../API
    ports:
      - "8082:80"
    networks:
      - api-network
      - api-db
  backend-postgres:
      container_name: backend-database
      image: "postgres:latest"
      environment:
        - POSTGRES_PASSWORD=password
        - POSTGRES_DB=backend
        - POSTGRES_USER=admin
      networks:
        - backend-db
      volumes:
        - /var/loans/postgres:/var/lib/postgresql/data
  api-postgres:
      container_name: api-database
      image: "postgres:latest"
      environment:
        - POSTGRES_PASSWORD=password
        - POSTGRES_DB=api
        - POSTGRES_USER=admin
      networks:
        - api-db
      volumes:
        - /var/loans/postgres-api:/var/lib/postgresql/data
networks:
  api-network:
    name: api-network
    driver: bridge
  backend-db:
    name: backend-db
    driver: bridge
  api-db:
    name: api-db
    driver: bridge