version: "3.5"
services:
  server:
    container_name: backend
    image: backend-dotnet
    build: .
    ports:
      - "8081:80"
  api:
    container_name: api
    image: apt-backend-dotnet
    build: ../../API/src
    ports:
      - "8082:80"
